package Emailpackage;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Scanner;

public class Email {
    private static final String DB_URL = "jdbc:oracle:thin:@localhost:1521:yourDatabaseName";
    private static final String USER = "yourUsername";
    private static final String PASS = "yourPassword";
    
    private Scanner sc = new Scanner(System.in);
    private String firstName;
    private String lastName;
    private String password;
    private String changpassword;
    private String department;
    private String email;
    private int mailboxCapacity;
    private String alternateEmail;

    // Constructor
    public Email(String firstName, String lastName) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.department = setDepartment();
        this.password = generateRandomPassword(10);
        this.mailboxCapacity = 500;
        this.email = createEmail();

        // Save email info to the database
        saveToDatabase();
    }

    private String setDepartment() {
        System.out.println("Department codes: \n1. Sales\n2. Development\n3. Accounting\n4. None\nEnter the department code:");
        int depChoice = sc.nextInt();
        switch (depChoice) {
            case 1:
                return "Sales";
            case 2:
                return "Development";
            case 3:
                return "Accounting";
            default:
                return "None";
        }
    }

    private String generateRandomPassword(int length) {
        String passwordSet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ@1234567890&#$*%";
        StringBuilder password = new StringBuilder(length);
        for (int i = 0; i < length; i++) {
            int rand = (int) (Math.random() * passwordSet.length());
            password.append(passwordSet.charAt(rand));
        }
        return password.toString();
    }

    private String createEmail() {
        return firstName.toLowerCase() + "." + lastName.toLowerCase() + "@" + department.toLowerCase() + "." + "company.com";
    }

    private void saveToDatabase() {
        try (Connection connection = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "system", "Vaibhav014")) {
            // Create table if it doesn't exist
            String createTableSQL = "CREATE TABLE EmailAccounts ("
                    + "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "firstName VARCHAR2(50), "
                    + "lastName VARCHAR2(50), "
                    + "email VARCHAR2(100), "
                    + "department VARCHAR2(50), "
                    + "password VARCHAR2(100), "
                    + "mailboxCapacity NUMBER)";
            Statement stmt = connection.createStatement();
            stmt.execute(createTableSQL);

            // Insert the email information
            String insertSQL = "INSERT INTO EmailAccounts (firstName, lastName, email, department, password, mailboxCapacity) VALUES (?, ?, ?, ?, ?, ?)";
            try (PreparedStatement pstmt = connection.prepareStatement(insertSQL)) {
                pstmt.setString(1, firstName);
                pstmt.setString(2, lastName);
                pstmt.setString(3, email);
                pstmt.setString(4, department);
                pstmt.setString(5, password);
                pstmt.setInt(6, mailboxCapacity);
                pstmt.executeUpdate();
            }

            System.out.println("Email account saved to the database.");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public String showInfo() {
        return "Display name: " + firstName + " " + lastName +
                "\nEmail: " + email +
                "\nMailbox capacity: " + mailboxCapacity + " MB";
    }

	public void changPassword(String newPassword) {
		// TODO Auto-generated method stub
		
	}
}
